CREATE TABLE users (
    id NUMBER(19,0) PRIMARY KEY,
    name VARCHAR2(100 CHAR) NOT NULL,
    email VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX idx_users_email ON users(email);
